name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      skip_build:
        description: 'Skip the build step and use the artifact from the last successful build (true/false)'
        required: false
        default: 'false'

jobs:
  build:
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.skip_build != 'true') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build strfry
        run: |
          sudo apt update && sudo apt install -y git g++ make pkg-config libtool \
          libssl-dev zlib1g-dev liblmdb-dev libflatbuffers-dev \
          libsecp256k1-dev libzstd-dev
          git submodule update --init
          make setup-golpe
          make -j4
          if ! [ -f ./strfry ]; then
             echo "Strfry build failed."
             exit 1
          fi

      - name: Package Debian (.deb)
        run: |
          sudo apt-get install debhelper devscripts -y
          dpkg-buildpackage --build=binary -us -uc
          mv ../*.deb .
          filename=$(ls *.deb | grep -v -- -dbgsym)
          echo "filename=${filename}" >> $GITHUB_OUTPUT

      - name: Upload strfry deb to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.package.outputs.filename }}
          tag: 'latest'
          name: 'Latest Build'
          draft: false
          prerelease: false
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download strfry deb from GitHub Release
        run: |
          GITHUB_API_URL="https://api.github.com/repos/${{ github.repository }}/releases/tags/latest"
          AUTH_HEADER="Authorization: token ${{ secrets.GITHUB_TOKEN }}"
          ASSET_ID=$(curl -s -H "$AUTH_HEADER" $GITHUB_API_URL | jq -r '.assets[] | select(.name | test("\\.deb$")) | .id')
          if [ -z "$ASSET_ID" ]; then
            echo "No .deb asset found in the latest release."
            exit 1
          fi
          curl -L -H "$AUTH_HEADER" -H "Accept: application/octet-stream" \
            "https://api.github.com/repos/${{ github.repository }}/releases/assets/$ASSET_ID" \
            -o strfry.deb

      - name: Deploy to AWS Server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ${{ secrets.AWS_SERVER_USER }}
          key: ${{ secrets.AWS_SERVER_SSH_KEY }}
          source: ./strfry.deb
          target: /tmp/strfry.deb

      - name: Install and Start on AWS Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ${{ secrets.AWS_SERVER_USER }}
          key: ${{ secrets.AWS_SERVER_SSH_KEY }}
          script: |
            sudo dpkg -i /tmp/strfry.deb
            sudo systemctl restart strfry

      - name: Deploy to Ali Server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.ALI_SERVER_IP }}
          username: ${{ secrets.ALI_SERVER_USER }}
          key: ${{ secrets.ALI_SERVER_SSH_KEY }}
          source: ./strfry.deb
          target: /tmp/strfry.deb

      - name: Install and Start on Ali Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.ALI_SERVER_IP }}
          username: ${{ secrets.ALI_SERVER_USER }}
          key: ${{ secrets.ALI_SERVER_SSH_KEY }}
          script: |
            sudo dpkg -i /tmp/strfry.deb
            sudo systemctl restart strfry
