name: Deploy

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download strfry deb
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.filename }}
          path: ./strfry.deb

      - name: Deploy to AWS Server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ${{ vars.AWS_SERVER_USER }}
          key: ${{ secrets.AWS_SERVER_SSH_KEY }}
          source: ./strfry.deb
          target: /tmp/strfry.deb

      - name: Install and Start on AWS Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ${{ vars.AWS_SERVER_USER }}
          key: ${{ secrets.AWS_SERVER_SSH_KEY }}
          script: |
            sudo dpkg -i /tmp/strfry.deb
            sudo systemctl restart strfry

      - name: Deploy to Ali Server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.ALI_SERVER_IP }}
          username: ${{ vars.ALI_SERVER_USER }}
          key: ${{ secrets.ALI_SERVER_SSH_KEY }}
          source: ./strfry.deb
          target: /tmp/strfry.deb

      - name: Install and Start on Ali Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.ALI_SERVER_IP }}
          username: ${{ vars.ALI_SERVER_USER }}
          key: ${{ secrets.ALI_SERVER_SSH_KEY }}
          script: |
            sudo dpkg -i /tmp/strfry.deb
            sudo systemctl restart strfry
